### ISSUE TITLE
Store commander "installer"

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/storecommander#1]
Hi,

We are supposed to validate a module, not a module downloader.
Please replace your code with the module supposed to be executed. We should not have to download any file in order to make our module working.

By the way, please note that the _PS_MODE_DEV_ does the same job as your DEBUG const.
Registering your module in the QuickAccess is also forbidden for partner modules. For the side menu, we can allow exception is some case.

**Comment by vincentmillet** [comment]
Hi,

You have only to test the installation module as described in the partner contract we signed (with Frédéric Vacher).

DEBUG const: it allows to test only our module and not the whole Prestashop installation which may display other error messages.

There is no installation in the QuickAccess menu: there is only code to uninstall from the QuickAccess menu for older version of the Store Commander installation in order to follow your guidelines.

**Comment by Quetzacoalt91** [comment]
We almost done with this module.

I still want you to remove the first part of the module class: 

``` php
if (Tools::getIsset("DEBUG")) {
    error_reporting(E_ALL ^ E_NOTICE);
    @ini_set('display_errors', 'on');
}
```

The code related to the variables `$this->currentUrl` and `$this->baseParams` can also be removed because not used anymore.

Finally,  please have a look at the report from https://validator.prestashop.com. A few things should be fixed before publishing the module.

Thanks
Best regards

**Comment by vincentmillet** [comment]
Ok it will be done quickly.

Do we need to include a module_key property in the module for Addons?

**Comment by Quetzacoalt91** [comment]
No, you don't have to. Partner modules are automatically considered as trusted modules.

**Comment by vincentmillet** [comment]
The module has been updated 1 week ago. You should receive notifications for code updates.

**Comment by Quetzacoalt91** [comment]
Hi,

Nope, notifications are not sent on push. I have just been notified thanks to your message.
Next time, do not forget to answer on the PR / issue to keep us in touch.

Best regards

**Comment by vincentmillet** [comment]
Ok so I reply again.
Please this is urgent now.

**Comment by Quetzacoalt91** [comment]
A lot of unused parts was still in the module, so I removed them by myself.
I will now publish the module. 

Best regards
